### ISSUE TITLE
EventStore docker should mount to nlog directory

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#122]
Our test trace is logged out to:

fileName="/home/runner/subscriptionservice/trace/${date:format=yyyyMMdd}/Trace.txt"

This is held in nlog.config.

We need to make sure we Mount the EventStore container to move the logs files here.

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - just noticed that LogMessageToTrace has the directory code.
Shouldn't we just do this once, rather than everything line we write out?
We could then cache the path, and use it for StartContainersForScenarioRun (just for the EventStore container)

**Comment by StuartFergusonVme** [comment]
Yeah could probably do that
