### ISSUE TITLE
Specflow initial test

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#13]
**Is your feature request related to a problem? Please describe.**
Simple specflow test which will prove the Subscription Service can be run against an Event Store (docker)

**Describe the solution you'd like**
Gherkin test which describes a new stream being created, then a persistent subscription created via the Subscription Service.
Persisted events should be delivered to some simple endpoint.

**Describe alternatives you've considered**
Nothing at this time.

**Additional context**
Nothing at this time.

**Comment by StevenBlair123** [comment]
What version of ES were you planning on running against?

**Comment by StuartFergusonVme** [comment]
v5.0.5 as its the latest official release

**Comment by StevenBlair123** [comment]
We should probably plan on running against multiple versions.
