### ISSUE TITLE
Example Code

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#20]
Add in example projects on hosting options:

- Console App
- REST Service
- Windows Service
- .NET Framework ??

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  -  I think this should be in the first version.

What did you mean by .NET Framework btw?

**Comment by StuartFergusonVme** [comment]
Showing that it can be used pre .net core.

**Comment by StuartFergusonVme** [comment]
Decision taken to not add REST example as service designed to support HTTP Posting to external endpoints.  

The standard example of adding the configuration into a REST service and dispatching the events locally is essentially bad design which this library is designed to replace.

NET Framework example moved into separate job due #65  to CI considerations.
