### ISSUE TITLE
Reconnect when subscription group is updated in Event Store UI

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#21]
**Is your feature request related to a problem? Please describe.**
When a subscription group is updated in the Event Store UI the group's connection is dropped, we need to reconnect when this happens

**Describe the solution you'd like**
When a config change is made the Subscription Service should be capable of reconnecting

**Describe alternatives you've considered**
None this is required

**Additional context**
Nothing at this time

**Comment by StevenBlair123** [comment]
Would this be better as a bug?

**Comment by StevenBlair123** [comment]
We really should try and replicate this and verify if we need to do anything.
