### ISSUE TITLE
New subscription configuration fields

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#22]
**Is your feature request related to a problem? Please describe.**
I would like to be able to fine tune each persistent subscription via configuration rather than use the defaults.

**Describe the solution you'd like**
New configuration fields are required to be added:

- Number of Concurrent messages 
- Max Retry Count (number of attempts before the message is parked)
- Message Timeout (How long before the event message is retried)
- Start Position (position within the stream from where to start reading events)

**Describe alternatives you've considered**
None these are required

**Additional context**
Nothing at this time

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - will Message Timeout be linked to the Http POST?

**Comment by StuartFergusonVme** [comment]
Yes it will but the Http Timeout will need to be less than the Event Store timeout value, maybe this should be a seperate field or a percentage of the Message Timeout config value ?

**Comment by StevenBlair123** [comment]
I aint sure.
Would this make the configuration a bit more confusing?

Maybe we just internally make that decision.

**Comment by StuartFergusonVme** [comment]
Probably best this is an internal decision, and we can open up in future if required.

**Comment by StevenBlair123** [comment]
@StuartFergusonVme - I think this should be in our first release.
