### ISSUE TITLE
Nightly Build CI Workflow

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#23]
Add a workflow to perform a scheduled nightly build.

**Comment by StuartFergusonVme** [comment]
Should this build a nightly nuget package as well ?

**Comment by StevenBlair123** [comment]
Will it only create it if there are changes?

**Comment by StuartFergusonVme** [comment]
No there is no way yet in Github CI to trigger if changes, it runs on a schedule regardless.

**Comment by StevenBlair123** [comment]
I don't think we want a new nuget every day. 
Imagine someone checked there nuget updates and saw a new package daily :\

**Comment by StevenBlair123** [comment]
Should we close this off?

**Comment by StuartFergusonVme** [comment]
Yeah we can reopen if required.
