### ISSUE TITLE
Url field - enforce validation?

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#24]
Should the Subscrition Value object enforce a valid Url is passed in?
It is currently a String.
Creating an Subscription Value object with an invalid Url would not be highlighted until we actually received some events and tried to deliver them.

**Comment by StevenBlair123** [comment]
Also begs the question whether the Subscription Value Object should guard against invalid StreamNames and GroupNames (null / empty)

My view would be they should be enforced.

**Comment by StuartFergusonVme** [comment]
I am in process of updating this to bring a uri object internally as per issue #8

**Comment by StevenBlair123** [comment]
What about the guards for the other fields then?
Would a Subscription Value object be deemed as valid with a null value for Stream Name?

**Comment by StuartFergusonVme** [comment]
There is an issue for that as well #9

**Comment by StevenBlair123** [comment]
Ok, I will close this off. Duplicate Issue.
