### ISSUE TITLE
Unit Tests for Subscription Service

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#31]
Add in some basic unit tests to prove the flow working as expected.

This will involve mocking up an IEventStoreConnection to provide event data to the Event Appeared method.

Some kind of mocking will also be required on the actual delivery of the event data to the configured consumer.

**Comment by StevenBlair123** [comment]
What's the plan for this?

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - we have coverage of this (I was modifying some today).
Should we close this off?

**Comment by StuartFergusonVme** [comment]
Yeah think thats probably best.
