### ISSUE TITLE
Update nuget details on nuget.org

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#38]
![image](https://user-images.githubusercontent.com/13871941/71182069-502b0e00-226d-11ea-8feb-d9795d1cc84b.png)

need to add some details in here (unsure where we set them yet)

Description - Meaningful description of that the package is.
Authors should be VME Retail Ltd
tags - eventstore vmeretail

**Comment by StuartFergusonVme** [comment]
These are set in the Package tab under Project properties.
