### ISSUE TITLE
Docker tests to run under Windows

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#44]
**Is your feature request related to a problem? Please describe.**
Docker tests will only run under Linux.

**Describe the solution you'd like**
Windows docker files for Event Store and REST endpoint to allow Windows testing

**Describe alternatives you've considered**

Not having Windows testing enabled.

**Comment by StuartFergusonVme** [comment]
For this to be supported the docker images would need to be built for multiple platforms.

At the moment we are tied by the fact that the EventStore docker image is built against only ubuntu linux.

**Comment by StevenBlair123** [comment]
Should we just close this off?

**Comment by StuartFergusonVme** [comment]
Yeah we are kinda tied by using the ES docker image to running on linux.  I will close this off
