### ISSUE TITLE
Integration testing for Event Store 6

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#55]
https://github.com/EventStore/EventStore/packages/68255

There is now a docker image available for Event Store 6, so our intergration testing should test against that (as well as 5).

The trick will be how we structure this in the Before test area.

Do we always start Event Store 5 and 6 and somehow in the test choose which container to use (so we could use Inline test data) or do we have different tests per version?

@StuartFergusonVme

**Comment by StevenBlair123** [comment]
Option 1 is to spin up multiple event stores
Option 2 is pass in the event store version number (so we only need one Event Store container) and use multiple yml files for CI (this means we get a badge per Event Store run)

**Comment by StuartFergusonVme** [comment]
This can be achieved by setting environment variables in the yaml file.

2 variables will be used:

- Docker Repository
- Image Name

These will be set on each workflow file with the appropriate version.

**Comment by StevenBlair123** [comment]
Sounds good to me.

**Comment by StuartFergusonVme** [comment]
It may be possible to use the Matrix configuration in the workflow file, similar to running the job on multiple OS versions, this needs a bit of digging to see how possible it may be.

**Comment by StuartFergusonVme** [comment]
https://github.com/EventStore/EventStore/issues/2311

**Comment by StuartFergusonVme** [comment]
https://github.com/EventStore/EventStore/issues/2344
