### ISSUE TITLE
Ability to change subscription configuration after object is created

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#56]
**Is your feature request related to a problem? Please describe.**
Currently the Subscription Service takes in a list of configuration items as part of its constructor that will be setup in Event Store as persistent subscriptions.

This operates fine but is a bit limited if the hosting process needs to add a new configuration there is no way this can be done.

**Describe the solution you'd like**
Update the object constructor to not accept the configuration list but instead this will be passed into the Start method.

This means that to update a "running" configuration the following code would be required.

```
String connectionString = "ConnectTo=tcp://admin:changeit@127.0.0.1:1113;VerboseLogging=true;";
IEventStoreConnection eventStoreConnection = EventStoreConnection.Create(new Uri(connectionString));

List<Subscription> subscriptions = new List<Subscription>();
subscriptions.Add(Subscription.Create("$ce-Accounts", "Read Model", new Uri("http://127.0.0.1/api/events")));

//You are responsible for the connection.
await eventStoreConnection.ConnectAsync();

SubscriptionService subscriptionService = new SubscriptionService(eventStoreConnection);

await subscriptionService.Start(subscriptions,CancellationToken.None);

subscriptions.Add(Subscription.Create("$ce-Transactions", "Read Model", new Uri("http://127.0.0.1/api/events")));

await subscriptionService.Start(subscriptions,CancellationToken.None);

```

The second call to the .Start() method will do the same action as the first call but will start the second persistent subscripton.  The first one will not be recreated.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by StuartFergusonVme** [comment]
@StevenBlair123

**Comment by StevenBlair123** [comment]
Yeah, I think this is the best way to go.
