### ISSUE TITLE
Add Number of Downloads Badge to Readme

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#57]
Add the following snippet to the readme file to show number of Nuget Downloads (this will be a total for all versions)

```
<a href="https://www.nuget.org/packages/EventStore.SubscriptionService">
  <img src="https://img.shields.io/nuget/dt/EventStore.SubscriptionService.svg" alt="NuGet Downloads" height="50">
</a>
```
Example:
<a href="https://www.nuget.org/packages/EventStore.SubscriptionService">
  <img src="https://img.shields.io/nuget/dt/EventStore.SubscriptionService.svg" alt="NuGet Downloads">
</a>

**Comment by StevenBlair123** [comment]
Looks cool
