### ISSUE TITLE
Catchup subscriptions discussion

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#59]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Allow a catchup subscription to be triggered

**Describe alternatives you've considered**
Continue not using them, and always use a Persistent Subscription.

**Comment by StevenBlair123** [comment]
This might require us to reshape the configuration.
Do we try to pass Persistent and Catchups through the same .Start (or Ctor) or create a new route on the service for triggering catchups?

For example:

subscriptionService.StartCatchupSubscriptions( catchups );

**Comment by StevenBlair123** [comment]
@StuartFergusonVme

**Comment by StuartFergusonVme** [comment]
Would a catch-up subscription not be something more of a one off so might make sense to have on a separate route in the service.

**Comment by StevenBlair123** [comment]
Yeah, I think so.

**Comment by StevenBlair123** [comment]
I think we need to push this up the priority list.

**Comment by StevenBlair123** [comment]
investigations/catchupInvestigation  - branch to review

Other issues we need to discuss:

1. Do catchups concurrently process events (I think it's one at a time)
2. If an event fails to process (from Event Appeared) does that block the catchup?
3. Assuming question 2 answer is block, does that mean there is no concept of a parked queue?
4. How can we identify if a catch subscription has stopped (API / UI)

**Comment by StevenBlair123** [comment]
Reconnect to the stream when there is a problem - should we keep doing this forever?

**Comment by StevenBlair123** [comment]
If an event fails to make it out of EventAppeared, should we introduce the concpet of writing the event to some kinda of customer parker queue.

@StuartFergusonVme  - would be good to het your feedback here, but we need to make sure we don't name clash with existing parked naming.

If we connected to a a stream "$ce-CatchupTest" on a persistent subscription it would be:

_$persistentsubscription-$ce-CatchupTest'e::QueryModel-parked_

How about we do this:

_$catchupsubscription-$ce-CatchupTest'::QueryModel-parked_

**Comment by StevenBlair123** [comment]
Also, @StuartFergusonVme  - this parked proposal, a separate job, or bundled up in this Issue?

**Comment by StevenBlair123** [comment]
We should offer a deadletter / parked queue facility. By default use EventStore as mentioned above, but also allow the user to inject their own.

**Comment by StuartFergusonVme** [comment]
> Also, Stuart Ferguson - this parked proposal, a separate job, or bundled up in this Issue?

I think its part of the same job to be honest.

**Comment by StevenBlair123** [comment]
Even if it involves an injected factory? Was speaking to someone yesterday and they write their catchup failed events to a NoSQL Database.

**Comment by StuartFergusonVme** [comment]
Maybe an injected factory should be a separate job but a default option should probably be provided in the first cut.

**Comment by StevenBlair123** [comment]
I was thinking we would inject a Default factory in, and then the users can choose to inhert from IParkedFactory (or whatever) themselves.
Happy enough to include the default handing in this job.

**Comment by StevenBlair123** [comment]
Development work reference here:

https://github.com/vmeretail/subscriptionservice/issues/96

**Comment by StevenBlair123** [comment]
I will leave this open for reference
