### ISSUE TITLE
Remove a Persistent Subscription Configuration

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#68]
**Is your feature request related to a problem? Please describe.**
There is currently no way to remove a persistent subscription configuration from a running Subscription Service other than stop and start the hosting process after the persistent subscription configuration has been removed from its configuration storage.

**Describe the solution you'd like**
A new method on the SubscriptionService class where the Name of the Stream and Group can be passed into and this will then call through to Event Store disconnecting from the Persistent Subscription and deleting this persistent subscription from Event Store.

**Describe alternatives you've considered**
None.

**Additional context**
Nothing at this time.

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - just to remind me about this.

We create a new route in the SS to let us delete a Persistent Subscirption, but the detection of this would sit within the hosting process / persistence layer?

**Comment by StuartFergusonVme** [comment]
Yeah thats right.

**Comment by StevenBlair123** [comment]
Milestone 1.0.2 ?

**Comment by StuartFergusonVme** [comment]
Well we could do, or could create a release of what is in master at the moment to get the Event Factory stuff live then move the other issues to a v1.0.3?
