### ISSUE TITLE
Allow users to pass in a factory for converting ResolvedEvents to serialised data

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#69]
**Is your feature request related to a problem? Please describe.**
We have noticed that the serialised data posted to the endpoint works from .Data on the ResolvedEvent. There is a requirement to bundle up information from the ResolvedEvent, but the OnEventAppeared does not give you access to this.

**Describe the solution you'd like**
Allow a factory to be injected into the Subscription Service, which allows custom code for return the serialised  data to be posted to endpoint.
When a factory is not injected, the default behaviour should be used.

**Describe alternatives you've considered**
None.

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - I think we should look at building something like IEventFactory exposing a method called:

_String ConvertFrom(ResolvedEvent @event);_

We could build a factory inside the nuget that does exactly as our EventAppeared does (maybe the factory will be internal):

_String serialisedData = Encoding.Default.GetString(resolvedEvent.Event.Data, 0, resolvedEvent.Event.Data.Length);_

If the user does not specify a factory, we simply default to this one so the EventAppeared flow always uses a factory.

**Comment by StuartFergusonVme** [comment]
Sounds good

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - I am going to decoiuple the RecordedEvent form the factory (since ES 6 looks like it will be changing the emitted type).

My suggestion is the factory expects a "PersistedEvent" - this means our EventAppeared will convert a RecordedEvent to a PersistedEvent.

Assuming you are agree, which fields should be allow the client to use?

Here are the current fields in RecordedEvent:

string EventStreamId;
Guid EventId;
long EventNumber;
string EventType;
byte[] Data;
byte[] Metadata;
bool IsJson;
DateTime Created;
long CreatedEpoch;

**Comment by StuartFergusonVme** [comment]
I would expose all fields to the user.
