### ISSUE TITLE
TraceGenerated - should we include more information

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#72]
When we make a call to TraceGenerated, we are passing a String message.

Once that event is eventually picked up by the hosting process, it will likely log a datetime  of the actual message being written, instead of when it happened.

We could make a small change in the code to allow the datettime to be set (probably hide this from the user) and pass it up to whoever is listening.

@StuartFergusonVme  - what do you think?

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - I have picked this up, and something isn't sittign right with this change.
If we have the DateTime being passed when we dispatch the trace event, it looks ok when we log to a Console. For example:

```
private static void SubscriptionService_TraceGenerated(DateTime datetime, String trace)
{
    Console.WriteLine($"{datetime} | {trace}");
}
```

But when you look at ane xample where the hosting process is using a Logger, now it seesm weird:

```
private void SubscriptionService_ErrorHasOccured(DateTime datetime,String trace)
{
    this.Logger.LogError(trace);
}
```

The Logger itself will a DateTime stamp of it's own, and we will be grafting our own DateTime in the actual message.
I suspect that is going to be pretty confusing.

What do you think?

**Comment by StevenBlair123** [comment]
I am wondering whether we should inject an ILogger in and let the client choose how the logging gets managed.

**Comment by StuartFergusonVme** [comment]
If the client is using their own logger does that not then mean they will have the same issue we added this requirement in for, i.e. they are not getting the **real** time in the logs

**Comment by StevenBlair123** [comment]
How?
So if you have this:

```
ILogger myLogger = someLoggerFactory();
SubscriptionService s = new SubscriptionService (myLogger );
```

Now, inside our code, we can log out whatever we want, rather than broadcasting the messages?

```
void EventAppeared(){
    //stuff

    this.Logger($"Event Id {resolvedEvent.Event.EventId} - Event POST successful");
}
```

**Comment by StuartFergusonVme** [comment]
Ah right, yes I misunderstood what you were saying above :|
