### ISSUE TITLE
Investigate using XunitContext in our integration tests

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#73]
Have a look at the library https://github.com/SimonCropp/XunitContext and see if this would be helpful in our integration tests for simplifying logging and catching test failures in a single place.

**Comment by StevenBlair123** [comment]
One for 1.0.2?

**Comment by StevenBlair123** [comment]
Anything else needing done here (if yes, move to milestone 1.0.4)

**Comment by StuartFergusonVme** [comment]
After investigating this library wont really provide us with any real benefit at the moment.
