### ISSUE TITLE
Worker Service to be included in repository.

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#74]
Include the Worker process as aprt of the main solution (no longer an example).

I think this will help people startout using the Subscription Service if give them a maintained version of the hosting process.

To be included:

1. Project becoming part of the main solution (and removed from our internal repository)
2. Instruction on front page on how to launch the process
3. Docker details no the hosted process (pull and run)

@kevinattard-vme to thank for this :P

**Comment by StuartFergusonVme** [comment]
Are we going to host the docker image on docker hub for this ?

This will also need updated as part of our Release CI process.

**Comment by StevenBlair123** [comment]
Yeah, I would say we should fofer a docker image for this as well.

**Comment by StevenBlair123** [comment]
This needs reviewed.
The problem will be the database persistence. Would this get bundled as well?

**Comment by StevenBlair123** [comment]
Suspect we will need to move all private solution across.

**Comment by StuartFergusonVme** [comment]
Decided that this will not really give the user any benefit mainly because how they set the configuration for the subscriptions could be different from the MS-SQL config structure we currently use.  This has been parked for now and can be revisited at a later date if required.
