### ISSUE TITLE
Log all events to trace

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#75]
@StuartFergusonVme  - the feature we recently plugged into one of our internal systems integration testing where we logged out all events (using a simple projection).
Do you think that would be useful in our testing?

**Comment by StuartFergusonVme** [comment]
I'm not sure how useful it will be to be honest, however for the effort it takes it's probably worth adding in, will probably be more useful in CI rather than locally though.

**Comment by StevenBlair123** [comment]
Althought, on CI we dont have access to the log files do we?

**Comment by StuartFergusonVme** [comment]
Only when using the SSH debug which trips on a failed PR

**Comment by StevenBlair123** [comment]
Ah right, so might still be worth doing it?
That would our event store log would have all the events written.
