### ISSUE TITLE
Log out event in the trace when NAK'd

### ISSUE THREAD

**Issue by StevenBlair123** [vmeretail/subscriptionservice#77]
When an event has failed to be delivered, we should serialise the data and bundle it up in the error message we broadcast.

We might want to consider allowing the user a way of controlling this (rather than a trace level as there might be security concerns with logging the events out).

Also, should we wait until this job #72 before attempting this?

@StuartFergusonVme

**Comment by StuartFergusonVme** [comment]
Yeah should wait on #72.

Agreed this will be fed in as a ctor parameter to log out event data on POST errors.

**Comment by StevenBlair123** [comment]
Optional parameter with the default not logging out events.

**Comment by StevenBlair123** [comment]
@StuartFergusonVme  - just noticed we have this code just before we attempt to deliver the event:

**Comment by StevenBlair123** [comment]
Or, keep it, and just have it controleld by the ctor value (as discussed earlier).
The only downside is, if a problem occured, you would have to sift through all the positive events.

**Comment by StuartFergusonVme** [comment]
I think we should keep it as might be useful for debugging but have a control flag on it for production use.

**Comment by StevenBlair123** [comment]
So what would the flag control?

All events logged
Only errors logged
No Events

How does this fit in with our ES projection logging events?

**Comment by StuartFergusonVme** [comment]
Yeah could have it as an enum with those values.

The ES Debug projection would write out to the Event Store logs but this would only log what has been written to Event Store not what out class has picked up and attempted to process.

**Comment by StevenBlair123** [comment]
Yeah, but our SS **only** works off data written to the EventStore, even in the delivery fails?
It just seems crazy having two paths to log out all events.
