### ISSUE TITLE
Add Supported Versions of Event Store to Readme

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#79]
Update Readme to have badges for Supported EventStore versions

**Comment by StevenBlair123** [comment]
Is this straight forward to do (i.e. for V 1.0.4.) ?

**Comment by StuartFergusonVme** [comment]
Well we can add static badges for now, what we cant do at the moment is have a badge per test run, not sure if GitHub CI will support this in future....

**Comment by StevenBlair123** [comment]
Should we just go with static badges for now, and look at doing this dynamically another time?
