### ISSUE TITLE
Accept Uri parameter in Subscription Configuration create method

### ISSUE THREAD

**Issue by StuartFergusonVme** [vmeretail/subscriptionservice#8]
**Is your feature request related to a problem? Please describe.**
When I create an instance of the subscription configuration object I am required to pass in a string representation of the endpoint's Uri rather than the actual Uri object.

**Describe the solution you'd like**
Allow the passing in of a Uri object.

**Describe alternatives you've considered**
None

**Additional context**
N/A

**Comment by StevenBlair123** [comment]
We will keep the .Create passing the String Uri, and introduce a second .Create passing a Uri instead.
Both methods will route to the same ctor, will will ultimately store a Uri.
